### PUT request to update patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "haint122231",
  "email": "haint1223@example.com",
  "address": "123 hanoi",
  "dateOfBirth": "2000-01-01"
}
###